# Generated by Django 4.2.1 on 2023-05-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientsInRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Количество')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_ingredient', to='recipes.recipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='amount',
            field=models.ManyToManyField(through='recipes.IngredientsInRecipes', to='recipes.ingredient'),
        ),
    ]
